# Generated by Django 5.2.6 on 2025-10-06 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0007_alter_person_profession_alter_place_feature_code_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="abbreviation",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="easydb4_reference",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="system_object_id",
        ),
        migrations.RemoveField(
            model_name="versioninstitution",
            name="abbreviation",
        ),
        migrations.RemoveField(
            model_name="versioninstitution",
            name="easydb4_reference",
        ),
        migrations.RemoveField(
            model_name="versioninstitution",
            name="system_object_id",
        ),
    ]
