# Generated by Django 5.2.6 on 2025-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0008_remove_institution_abbreviation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninstitution",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
